### ISSUE TITLE
Support Vert.x Shell

### ISSUE THREAD

**Issue by nolequen** [nolequen/vertx-prometheus-metrics#1]
Implement on-fly configuration via Vert.x Shell commands.

**Comment by boliza** [comment]
just like vertx-dropwizard-metrics?

**Comment by nolequen** [comment]
yes, it would be great!

**Comment by boliza** [comment]
I do other impl:  [vertx-prometheus-metrics](https://github.com/shikeio/vertx-prometheus-metrics)
Idea from the [Example](https://github.com/vert-x3/vertx-examples/blob/master/metrics-examples/src/main/java/io/vertx/example/metrics/prometheus/PrometheusMetricsVerticle.java)

**Comment by nolequen** [comment]
I think, it's good idea to use dropwizard metrics and export it to prometheus. But current implementation tries not to use any dependencies in-between vert.x and prometheus.

**Comment by boliza** [comment]
Vert.x has refactor vertx-metrics to support many backend. See the disscuss:https://groups.google.com/forum/#!topic/vertx-dev/40XfT3urRck

**Comment by nolequen** [comment]
Thanks for the info!
