### ISSUE TITLE
Missing exported metrics with multiple HTTP clients

### ISSUE THREAD

**Issue by brasseld** [nolequen/vertx-prometheus-metrics#16]
Hi guys, 

Congrats, you have done a really nice job with this Prometheus metrics module!

However, I think this one does not handle properly the fact that you can have multiple HTTP server and / or multiple HTTP client used in the same time. In that particular case, I'm always seeing the same HTTP server metrics and the same HTTP client metrics even if I have one hundred of HTTP clients used in //.

WDYT ?

**Comment by nolequen** [comment]
Hi @brasseld,

Thanks for your attention to the project. Could you please provide more detailed information (maybe with an example) to clarify the issue?

**Comment by jansorg** [comment]
@nolequen @brasseld I've fixed this at https://github.com/nolequen/vertx-prometheus-metrics/pull/19

**Comment by brasseld** [comment]
Nice !

Will have a try asap !
