### ISSUE TITLE
Several enhancements 

### ISSUE THREAD

**Issue by marcust** [nolequen/vertx-prometheus-metrics#20]
Hey, 

thanks for the good work, that was kind of in the direction what I was looking for. I forked for now because I wanted to try a couple of things before I knew that I want to proceed with that. I want to get the stuff back upstream but wanted to talk to you first to see what you think about certain changes. Are you on Gitter, then we can talk more directly? My changes are in https://github.com/hubrick/vertx-prometheus-metrics/tree/experimental/new-spis, I'm working on two Vert.x Core PRs to get more information through the SPI, which I will explain below.

Here are my points:
# Default for `embeddedServerEnabled`
To be honest it just does not really fit my use-case, because we have our own endpoints for Prometheus. One could argue that it might be not very intuitive to get a new endpoint from a metrics-SPI, but that is more because it does not fit my use-case. At least I need a 'setEmbeddedServerEnabled` because we are using the old `Starter` and this is the way to get that disabled (although I'm not looking forward to have that in all my services command line. I can PR that.

# More SPIs
I want to measure how busy the Event Loop is, so I added https://github.com/eclipse/vert.x/pull/2355, once that is merged I will PR that for your next version. 

# Host vs. Path based metrics
In my use-case it is not very practical to have the `path` in either the Client or the Server metrics because they have a far to high cardinality, because there are IDs in there. I think for my use-case having them based on host and then HTTP method might give some insights. First I have to get the access to the client request host into Vert.x (https://github.com/eclipse/vert.x/pull/2348) but then I think this can go back into your version with an option (like `enableHostFor(Client|Server)RequestMetrics` or the other way around (`enablePath`). I kind of throw it into our application and then out of a sudden had 10MB Prometheus responses, this is the reason why I would argue to make the host based metrics the default. 

So, what do you think of that?

**Comment by nolequen** [comment]
Hi @marcust,

Thanks for you attention to the project.
You can find me on gitter, but it is more comfortable for me to discuss your suggestions here.

> Default for embeddedServerEnabled

You can use `VertxPrometheusOptions.enableEmbeddedServer(false)` to disable embedded server.
It is enabled by default, but I can't find serious reason not to change this. Feel free to make the PR.

> More SPIs

I think, it is great idea! Waiting for your PR to be merged.

> Host vs. Path based metrics

Looks fine too. Of course, it should be configurable via `VertxPrometheusOptions`

**Comment by marcust** [comment]
Ok, all the code is there and the combination does what I want. Now let's just wait on Vert.x, then I will officially PR the two others.
